# Generated by Django 5.1.15 on 2026-09-28 16:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company / Business Name')),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('phone', models.CharField(max_length=20, verbose_name='Business Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Business Email')),
                ('address', models.TextField(blank=True, verbose_name='Office Address')),
                ('currency_symbol', models.CharField(default='₹', max_length=5)),
                ('skip_sundays_in_daily', models.BooleanField(default=True, help_text='If checked, daily loan repayment schedules will automatically skip Sundays.', verbose_name='Skip Sundays in Daily Loans')),
                ('trial_starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_status', models.CharField(choices=[('TRIALING', 'Trialing (30 Days)'), ('ACTIVE', 'Active Subscription'), ('EXPIRED', 'Expired / Payment Required'), ('CANCELLED', 'Cancelled')], default='TRIALING', max_length=20)),
                ('razorpay_customer_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_subscription_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('OWNER', 'Company Owner / Admin'), ('MANAGER', 'Operations Manager'), ('AGENT', 'Field Collection Agent')], default='OWNER', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('daily_collection_target', models.DecimalField(decimal_places=2, default=0.0, help_text='Target amount in ₹ expected per day for field collections', max_digits=12)),
                ('is_active_agent', models.BooleanField(default=True, help_text='Designates whether this agent can currently record collections in the field.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.company')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['role', 'first_name', 'username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
