# Generated by Django 5.1.15 on 2026-09-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('company_name', models.CharField(max_length=200, verbose_name='Finance Company Name')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='City / State')),
                ('loan_types_interested', models.CharField(blank=True, max_length=200, verbose_name='Loan Types')),
                ('notes', models.TextField(blank=True, verbose_name='Additional Information')),
                ('is_contacted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Demo Request',
                'verbose_name_plural': 'Demo Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
