# Generated by Django 5.1.15 on 2026-09-28 16:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(db_index=True, max_length=60, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Collected (₹)')),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI / QR Code'), ('BANK_TRANSFER', 'Bank Transfer / NEFT'), ('CHEQUE', 'Cheque')], default='CASH', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='UPI Ref / Cheque No.')),
                ('payment_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_advance', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collections_recorded', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.company')),
                ('installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='loans.installment')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.loan')),
            ],
            options={
                'verbose_name': 'Payment / Collection',
                'verbose_name_plural': 'Payments / Collections',
                'ordering': ['-payment_date'],
            },
        ),
    ]
