# Generated by Django 5.1.15 on 2026-09-28 16:39

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('loan_collections', '0001_initial'),
        ('loans', '0002_loan_closure_reason_loan_route_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='penalty_collected',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Penalty Collected (₹)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='penalty_waived',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Penalty Waived (₹)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='waiver_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='Penalty Waiver Reason'),
        ),
        migrations.CreateModel(
            name='CollectionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reason', models.CharField(choices=[('SHOP_CLOSED', 'Shop / Stall Closed'), ('NOT_AVAILABLE', 'Customer Not Available / Out of Station'), ('PROMISED_LATER', 'Promised to Pay Later'), ('DISPUTE', 'Dispute / Refused to Pay'), ('INSUFFICIENT_FUNDS', 'Cash Shortage / Arranging Funds'), ('OTHER', 'Other Reason')], default='PROMISED_LATER', max_length=30)),
                ('promised_date', models.DateField(blank=True, null=True, verbose_name='Promised Payment Date')),
                ('notes', models.TextField(blank=True, verbose_name='Agent Visit Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_attempts_logged', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_attempts', to='accounts.company')),
                ('installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_attempts', to='loans.installment')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_attempts', to='loans.loan')),
            ],
            options={
                'verbose_name': 'Collection / Visit Attempt',
                'verbose_name_plural': 'Collection / Visit Attempts',
                'ordering': ['-attempt_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyCashClosing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('count_500', models.PositiveIntegerField(default=0, verbose_name='₹500 Notes')),
                ('count_200', models.PositiveIntegerField(default=0, verbose_name='₹200 Notes')),
                ('count_100', models.PositiveIntegerField(default=0, verbose_name='₹100 Notes')),
                ('count_50', models.PositiveIntegerField(default=0, verbose_name='₹50 Notes')),
                ('count_20', models.PositiveIntegerField(default=0, verbose_name='₹20 Notes')),
                ('count_10', models.PositiveIntegerField(default=0, verbose_name='₹10 Notes')),
                ('count_coins', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='Coins Total (₹)')),
                ('total_physical_cash', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Counted Cash (₹)')),
                ('system_cash_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='System Cash Collected (₹)')),
                ('variance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Variance / Difference (₹)')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted by Agent'), ('VERIFIED', 'Verified & Accepted by Manager'), ('DISCREPANCY', 'Discrepancy / Shortage Reported')], default='SUBMITTED', max_length=20)),
                ('remarks', models.TextField(blank=True, verbose_name='Closing Remarks / Handover Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_closings_submitted', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_closings', to='accounts.company')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_closings_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Cash Closing',
                'verbose_name_plural': 'Daily Cash Closings',
                'ordering': ['-closing_date', '-created_at'],
                'unique_together': {('company', 'agent', 'closing_date')},
            },
        ),
    ]
