# Generated by Django 5.1.15 on 2026-09-28 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_code', models.CharField(db_index=True, max_length=30, verbose_name='Member / Customer ID')),
                ('name', models.CharField(max_length=150, verbose_name='Full Name')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='Mobile Number')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('address', models.TextField(verbose_name='Residential Address')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('area_or_route', models.CharField(blank=True, help_text='Helpful for grouping collections by route or locality', max_length=120, verbose_name='Route / Area Name')),
                ('id_proof_type', models.CharField(choices=[('AADHAAR', 'Aadhaar Card'), ('PAN', 'PAN Card'), ('VOTER_ID', 'Voter ID'), ('RATION_CARD', 'Ration Card'), ('DRIVING_LICENSE', 'Driving License')], default='AADHAAR', max_length=30)),
                ('id_proof_number', models.CharField(blank=True, max_length=50, verbose_name='ID Number')),
                ('id_proof_file', models.FileField(blank=True, null=True, upload_to='kyc_docs/', verbose_name='KYC Document')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='member_photos/', verbose_name='Customer Photo')),
                ('guarantor_name', models.CharField(blank=True, max_length=150, verbose_name='Guarantor Name')),
                ('guarantor_phone', models.CharField(blank=True, max_length=20, verbose_name='Guarantor Phone')),
                ('guarantor_relation', models.CharField(blank=True, max_length=50, verbose_name='Relationship with Borrower')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_members', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Collection Agent')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'member_code')},
            },
        ),
    ]
