# Generated by Django 5.1.15 on 2026-09-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='landmark',
            field=models.CharField(blank=True, help_text='e.g. Opp. Murugan Temple, Behind Bus Stand', max_length=150, verbose_name='Nearby Landmark'),
        ),
        migrations.AddField(
            model_name='member',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='GPS Latitude'),
        ),
        migrations.AddField(
            model_name='member',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='GPS Longitude'),
        ),
        migrations.AddField(
            model_name='member',
            name='visit_order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Sequence number for the agent walking route (e.g. 1, 2, 3...)', verbose_name='Walk / Visit Order'),
        ),
    ]
