# Generated by Django 5.1.15 on 2026-09-28 16:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Plan Name')),
                ('loan_type', models.CharField(choices=[('DAILY', 'Daily Collection'), ('WEEKLY', 'Weekly Collection'), ('MONTHLY_EMI', 'Monthly EMI (Principal + Interest)'), ('MONTHLY_INTEREST', 'Monthly Interest Only (Bullet Principal at End)'), ('WEEKLY_INTEREST', 'Weekly Interest Only (Bullet Principal at End)')], default='DAILY', max_length=25)),
                ('default_interest_rate_percent', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=6, verbose_name='Interest Rate (%)')),
                ('default_duration_units', models.PositiveIntegerField(default=100, verbose_name='Duration (Days / Weeks / Months)')),
                ('processing_fee_percent', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=6, verbose_name='Processing Fee (%)')),
                ('penalty_rate_percent', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, verbose_name='Late Penalty Fee (% or ₹/day)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_plans', to='accounts.company')),
            ],
            options={
                'verbose_name': 'Loan Plan',
                'verbose_name_plural': 'Loan Plans',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_account_no', models.CharField(db_index=True, max_length=50, verbose_name='Loan Account No.')),
                ('loan_type', models.CharField(choices=[('DAILY', 'Daily Collection'), ('WEEKLY', 'Weekly Collection'), ('MONTHLY_EMI', 'Monthly EMI (Principal + Interest)'), ('MONTHLY_INTEREST', 'Monthly Interest Only (Bullet Principal at End)'), ('WEEKLY_INTEREST', 'Weekly Interest Only (Bullet Principal at End)')], default='DAILY', max_length=25)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Loan Principal (₹)')),
                ('interest_rate_percent', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Interest Rate (%)')),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Interest Amount (₹)')),
                ('processing_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Processing Fee (₹)')),
                ('disbursed_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Disbursed Amount (₹)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Repayable (₹)')),
                ('start_date', models.DateField(verbose_name='Start / First EMI Date')),
                ('end_date', models.DateField(verbose_name='Maturity Date')),
                ('number_of_installments', models.PositiveIntegerField(verbose_name='No. of Installments')),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='EMI / Installment (₹)')),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed / Paid Off'), ('DEFAULTED', 'Defaulted / NPA')], default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_loans', to=settings.AUTH_USER_MODEL, verbose_name='Collection Agent')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='accounts.company')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='members.member')),
                ('loan_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loans', to='loans.loanplan')),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ['-created_at'],
                'unique_together': {('company', 'loan_account_no')},
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField()),
                ('due_date', models.DateField(db_index=True)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('pending_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue')], db_index=True, default='PENDING', max_length=20)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='loans.loan')),
            ],
            options={
                'verbose_name': 'Installment',
                'verbose_name_plural': 'Installments',
                'ordering': ['loan', 'installment_number'],
                'unique_together': {('loan', 'installment_number')},
            },
        ),
    ]
