# Generated by Django 5.1.15 on 2026-09-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='closure_reason',
            field=models.CharField(blank=True, choices=[('COMPLETED', 'Completed / Fully Paid'), ('SETTLED', 'Settled / Compromise'), ('BAD_DEBT', 'Bad Debt / Default Write-off'), ('DECEASED', 'Deceased Borrower'), ('ABSCONDED', 'Absconded / Untraceable'), ('LEGAL_ACTION', 'Legal Action Initiated')], max_length=30, verbose_name='Loan Closure Reason'),
        ),
        migrations.AddField(
            model_name='loan',
            name='route_sequence',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Custom order along the collection route', verbose_name='Route Sequence'),
        ),
    ]
